version: '3.8'

services:
  csv-analyzer-mcp:
    build: .
    environment:
      - E2B_API_KEY=${E2B_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp:rw
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M