version: '3.8'

services:
  crewai:
    build: .
    container_name: crewai-e2b
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - E2B_API_KEY=${E2B_API_KEY}
      - MAX_CONCURRENT_SANDBOXES=${MAX_CONCURRENT_SANDBOXES:-2}
      - MAX_SANDBOXES_PER_HOUR=${MAX_SANDBOXES_PER_HOUR:-20}
      - CODE_EXECUTION_TIMEOUT=${CODE_EXECUTION_TIMEOUT:-30.0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    mem_limit: 1g
    cpus: 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
