execute_task:
  description: |
    Calculate how many times the letter 'r' appears in the word 'strawberry'.
    
    IMPORTANT:
    - Think analytically first
    - Consider if you can solve without running code
    - If code is needed, write optimal code that runs once
    - Each execution costs money
    
    Choose the most efficient approach.
  expected_output: |
    Clear answer with:
    1. The exact count of 'r' in 'strawberry'
    2. Your reasoning
    3. Code used (if any)
    4. Verification